### ISSUE TITLE
Acesso de escrita

### ISSUE THREAD

**Issue by JoaoGFarias** [ebl4/distribution-enterprise-bigdata#3]
@ebl4,

Eu, @leoribeiro36 e @gcpa temos acesso de escrita ao repositório?
Fiz o clone, mas estou tomando erro de acesso.

**Comment by JoaoGFarias** [comment]
Up
@ebl4
@gcpa
@leoribeiro36

**Comment by ebl4** [comment]
Esqueci de colocar como colaborador. Atualizei e inseri
